import { useState } from 'react';

export function Preferences() {
    const [preferences, setPreferences] = useState({
        explanationMode: 'developer' as 'developer' | 'pm' | 'onboarding',
        autoGenerateDocs: true,
        theme: 'light' as 'light' | 'system',
    });

    const handleChange = (key: string, value: any) => {
        setPreferences({ ...preferences, [key]: value });
        // TODO: Auto-save to API
    };

    return (
        <div className="space-y-8">
            <div>
                <h2 className="text-2xl font-black text-gray-900 tracking-tight">Preferences</h2>
                <p className="text-sm font-medium text-gray-500 mt-2">
                    Control default behavior and settings.
                </p>
            </div>

            <div className="space-y-6">
                {/* Explanation Mode */}
                <div className="bg-white border border-gray-200 rounded-2xl p-6">
                    <h3 className="text-sm font-bold text-gray-900 mb-4">Default Explanation Mode</h3>
                    <div className="space-y-3">
                        {[
                            { value: 'developer', label: 'Developer', desc: 'Technical, code-focused explanations' },
                            { value: 'pm', label: 'Product Manager', desc: 'Business-oriented descriptions' },
                            { value: 'onboarding', label: 'Onboarding', desc: 'Beginner-friendly context' },
                        ].map((option) => (
                            <label
                                key={option.value}
                                className="flex items-start gap-3 p-4 bg-gray-50 rounded-xl cursor-pointer hover:bg-gray-100 transition-colors"
                            >
                                <input
                                    type="radio"
                                    name="explanationMode"
                                    value={option.value}
                                    checked={preferences.explanationMode === option.value}
                                    onChange={(e) => handleChange('explanationMode', e.target.value)}
                                    className="mt-0.5 h-4 w-4 text-indigo-600 focus:ring-indigo-500"
                                />
                                <div>
                                    <div className="text-sm font-bold text-gray-900">{option.label}</div>
                                    <div className="text-xs font-medium text-gray-500 mt-0.5">{option.desc}</div>
                                </div>
                            </label>
                        ))}
                    </div>
                </div>

                {/* Auto-Generate Docs */}
                <div className="bg-white border border-gray-200 rounded-2xl p-6">
                    <div className="flex items-center justify-between">
                        <div>
                            <h3 className="text-sm font-bold text-gray-900">Auto-Generate Documentation</h3>
                            <p className="text-xs font-medium text-gray-500 mt-1">
                                Automatically create docs when schema updates
                            </p>
                        </div>
                        <button
                            onClick={() => handleChange('autoGenerateDocs', !preferences.autoGenerateDocs)}
                            className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${preferences.autoGenerateDocs ? 'bg-indigo-600' : 'bg-gray-200'
                                }`}
                        >
                            <span
                                className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${preferences.autoGenerateDocs ? 'translate-x-6' : 'translate-x-1'
                                    }`}
                            />
                        </button>
                    </div>
                </div>

                {/* Theme */}
                <div className="bg-white border border-gray-200 rounded-2xl p-6">
                    <h3 className="text-sm font-bold text-gray-900 mb-4">Theme</h3>
                    <div className="space-y-3">
                        {[
                            { value: 'light', label: 'Light', desc: 'Always use light mode' },
                            { value: 'system', label: 'System', desc: 'Match system preferences' },
                        ].map((option) => (
                            <label
                                key={option.value}
                                className="flex items-start gap-3 p-4 bg-gray-50 rounded-xl cursor-pointer hover:bg-gray-100 transition-colors"
                            >
                                <input
                                    type="radio"
                                    name="theme"
                                    value={option.value}
                                    checked={preferences.theme === option.value}
                                    onChange={(e) => handleChange('theme', e.target.value)}
                                    className="mt-0.5 h-4 w-4 text-indigo-600 focus:ring-indigo-500"
                                />
                                <div>
                                    <div className="text-sm font-bold text-gray-900">{option.label}</div>
                                    <div className="text-xs font-medium text-gray-500 mt-0.5">{option.desc}</div>
                                </div>
                            </label>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
}
